/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NGORole;

import Business.WorkQueue.FoodRequirementRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pavansomashekar
 */
public class ProcessNWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessNWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private FoodRequirementRequest request;
    
    public ProcessNWorkRequestJPanel(JPanel userProcessContainer, FoodRequirementRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        groupButton();
    }

    private void groupButton( ) {

    ButtonGroup bg1 = new ButtonGroup( );
    bg1.add(radioApproved);
    bg1.add(radioRejected);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radioRejected = new javax.swing.JRadioButton();
        radioApproved = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setBackground(new java.awt.Color(247, 183, 13));
        submitJButton.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit Result");
        submitJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 276, 219, 35));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Result:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 195, -1, -1));

        backJButton.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 102, 102));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 317, 219, 32));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 180, 50));
        jLabel2.setText("Processing Request");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 25, -1, -1));

        radioRejected.setForeground(new java.awt.Color(51, 51, 51));
        radioRejected.setText("Rejected");
        add(radioRejected, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 230, -1, -1));

        radioApproved.setForeground(new java.awt.Color(51, 51, 51));
        radioApproved.setText("Approved");
        add(radioApproved, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 195, -1, -1));

<<<<<<< Updated upstream
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/proces.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 117, 252, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Union1.png"))); // NOI18N
=======
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 117, 252, -1));

>>>>>>> Stashed changes
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 530, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
         
        if(radioApproved.isSelected()){   
           // request.setRequestResult("Approved");
            request.setStatus("Completed");
             JOptionPane.showMessageDialog(null, "Request Approved!");
            
         }
        else if(radioRejected.isSelected()){
           // request.setRequestResult("Rejected");
            request.setStatus("Rejected");
            JOptionPane.showMessageDialog(null, "Request Rejected!");
        }
        else if(!(radioApproved.isSelected()) && !(radioRejected.isSelected())){
            
            JOptionPane.showMessageDialog(null, "Please select a result!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NGOWorkAreaJPanel dwjp = (NGOWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton radioApproved;
    private javax.swing.JRadioButton radioRejected;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
